#############################
#############################
## Automatic Build GCC_ARM ##
#############################
#############################

name: Build GCC_ARM

###############################
# Start the job on edited cpp #
###############################
on:
  pull_request:
    branches: [ main ]
    paths:
    - 'include/**'
    - 'src/**'
  push:
    branches: [ main ]
    paths:
    - 'include/**'
    - 'src/**'

###############
# Set the Job #
###############
jobs: 
  build-cli-gcc:

    container:
      image: nazmiropi/esp-buggy:tools

    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [NUCLEO_F401RE]
        profile: [release, debug, develop]
        
    steps:

      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v3
      
      # Compile using mbed-cli (GCC_ARM)
      - name: Build source code
        id: compile
        run: |
          set -e
          mbed new .
          mbed deploy
          mbed compile -t GCC_ARM -m ${{ matrix.target }} --profile ${{ matrix.profile }}
      
      # Log current time
      - name: Log current time
        run: echo "TIME=$(date +"%Y.%m.%d %H:%M")" >> $GITHUB_ENV

      # If success, update badge to green
      - name: Update badge to green
        if: steps.compile.outcome == 'success'
        uses: schneegans/dynamic-badges-action@v1.1.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 661bc6f35f626bca218501f160893b4b
          filename: gcc_badge.json
          label: Build GCC_ARM
          message: passing @ ${{ env.TIME }}
          color: green

      # If success, update badge to red
      - name: Update badge to red
        if: steps.compile.outcome != 'success'
        uses: schneegans/dynamic-badges-action@v1.1.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 661bc6f35f626bca218501f160893b4b
          filename: gcc_badge.json
          label: Build GCC_ARM 
          message: failing @ ${{ env.TIME }}
          color: red