####################
####################
## Style Check CI ##
####################
####################

name: Style Check


##############################
# Start the job on pull/push #
##############################
on:
  push:
    paths-ignore: "docs/**"
    branches: [main]
  pull_request:
    branches: [main]
    paths-ignore: "docs/**"

###############
# Set the Job #
###############
jobs:
  cpp-linter:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: C++ Lint
        id: check
        uses: reviewdog/action-cpplint@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          flags: "--exclude=include/DSP/*.h --exclude=src/DSP/*.h --exclude=src/DSP/*.c"
          filter: "-whitespace/indent\
            ,-legal/copyright\
            ,-build/header_guard\
            ,-build/include_subdir\
            "

      # If success, update badge to green
      - name: Update badge to green
        if: steps.check.outcome == 'success'
        uses: schneegans/dynamic-badges-action@v1.1.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 88852f73e80cb06c05e5babaec5febe0
          filename: lint_badge.json
          label: cpp-lint
          message: passing
          color: green

      # If fail, update badge to red
      - name: Update badge to red
        if: steps.check.outcome != 'success'
        uses: schneegans/dynamic-badges-action@v1.1.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 88852f73e80cb06c05e5babaec5febe0
          filename: lint_badge.json
          label: cpp-lint
          message: failing
          color: red

