# This is a basic workflow to help you get started with Actions

name: Doxygen Action

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]


  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
        
    - name: Doxygen Action
      id : build
      uses: mattnotmitt/doxygen-action@v1.9.3
      with:
        # Path to Doxyfile
        doxyfile-path: "./Doxyfile-prj.cfg" # default is ./Doxyfile
        # Working directory
        working-directory: "." # default is .
    
    -
      name: badge_green
      if: steps.build.outcome == 'success'
      uses: schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 25d7b5dd85bdd54d9dc73366aa9f4c85
        filename: doxygen_badge.json
        label: Doxygen
        message: passing
        color: green

    -
      name: badge_red
      if: steps.build.outcome == 'failure'
      uses: schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 25d7b5dd85bdd54d9dc73366aa9f4c85
        filename: doxygen_badge.json
        label: Doxygen
        message: failing
        color: red
