##################################
##################################
## Automatic Doxygen Deployment ##
##################################
##################################

name: Doxygen Action

##############################
# Start the job on push docs #
##############################
on:
  push:
    branches: [ main ]
    paths:
    - 'docs/**'

###############
# Set the Job #
###############
jobs:
  build:

    name: Doxygen Action
    runs-on: ubuntu-latest

    steps:
    # Build Documentation
    - uses: actions/checkout@v3
    - name: Build documentation
      uses: mattnotmitt/doxygen-action@v1.9.3
      with:
        doxyfile-path: "./Doxyfile-prj.cfg"
        working-directory: "docs/"

    # Deploy to gh-pages
    - name: Deploy documentation
      id : deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/html
    
    # Log current time
    - name: Log current time
      run: echo "TIME=$(date +"%Y.%m.%d %H:%M")" >> $GITHUB_ENV

    # If success, update badge to green
    - name: Update badge to green
      if: steps.deploy.outcome == 'success'
      uses: schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 25d7b5dd85bdd54d9dc73366aa9f4c85
        filename: doxygen_badge.json
        label: Doxygen
        message: passing @ ${{ env.TIME }}
        color: green

    # If fail, update badge to red
    - name: Update badge to red
      if: steps.deploy.outcome != 'success'
      uses: schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 25d7b5dd85bdd54d9dc73366aa9f4c85
        filename: doxygen_badge.json
        label: Doxygen
        message: failing @ ${{ env.TIME }}
        color: red
